apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sandbox-controller-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log"]
  verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sandbox-controller-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: sandbox-controller
  namespace: default
roleRef:
  kind: Role
  name: sandbox-controller-role
  apiGroup: rbac.authorization.k8s.io